name: Node.js CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npx nyc mocha
      - name: Upload Coverage to Coveralls
        run: npx nyc report --reporter=text-lcov | npx coveralls
